### ISSUE TITLE
最新版本的镜像有两个下载不了  i can't download tispark-master and tispark-slave0 images

### ISSUE THREAD

**Issue by smallyaohailu** [pingcap/tidb-docker-compose#106]
在执行完第二句后，发现两个镜像无法下载：

after i click two command 

`$ git clone https://github.com/pingcap/tidb-docker-compose.git
$ cd tidb-docker-compose && docker-compose pull # Get the latest Docker images
`

**Pulling tispark-master
Pulling tispark-slave0** 

Pulling pd0            ... done
Pulling pd1            ... done
Pulling pd2            ... done
Pulling tikv0          ... done
Pulling tikv1          ... done
Pulling tikv2          ... done
Pulling tidb           ... done
**Pulling tispark-master ... retrying in 1 second
Pulling tispark-slave0 ... retrying in 1 second**
Pulling tidb-vision    ... done
Pulling pushgateway    ... done
Pulling prometheus     ... done
Pulling grafana        ... done

**Comment by smallyaohailu** [comment]
after i use  
**docker pull pingcap/tispark:v2.1.1** 

i download it ,thanks

**Comment by sunxiaoguang** [comment]
Hi @smallyaohailu, thanks for reporting this issue. Running TiDB with docker compose is legacy solution, you can try tiup which is a lot easier to use. 

You may take a look at here: https://docs.pingcap.com/tidb/stable/production-deployment-using-tiup

**Comment by smallyaohailu** [comment]
> Hi @smallyaohailu, thanks for reporting this issue. Running TiDB with docker compose is legacy solution, you can try tiup which is a lot easier to use.
> 
> You may take a look at here: https://docs.pingcap.com/tidb/stable/production-deployment-using-tiup

thank you very mush , i know , https://gitee.com/mirrors/TiUP

the new prd install method:
https://gitee.com/mirrors/TiUP
https://gitee.com/mirrors/TiUP
https://gitee.com/mirrors/TiUP
