### ISSUE TITLE
Using docker-compose to start results in the following error on windows

### ISSUE THREAD

**Issue by chenzhe** [pingcap/tidb-docker-compose#13]
```
PD  :/data/pd0/member/wal.tmp /data/pd0/member/wal: permission denied
```

**Comment by tennix** [comment]
Sorry, I don't have a Windows machine at hand. But after some googling, it seems like a docker-compose [bug](https://stackoverflow.com/questions/37666462/docker-compose-up-permission-denied-on-windows). You can try if chmod works for you

**Comment by Hoverbear** [comment]
@chenzhe Did this help you?

**Comment by tennix** [comment]
Close this issue. If this still doesn't solve your problem, feel free to reopen it
