### ISSUE TITLE
can not deploy via docker-compose successfully

### ISSUE THREAD

**Issue by eric2016fly** [pingcap/tidb-docker-compose#20]
My docker-compose version:
docker-compose version 1.21.2, build a133471
and docker version:
Docker version 1.13.1, build 87f2fab/1.13.1

I pulled the docker images successfully.  see below:

docker images
REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
docker.io/pingcap/pd                         latest              95036bbd8644        8 hours ago         72.3 MB
docker.io/pingcap/tidb-dashboard-installer   v1.0.0              c4dbc1379ec7        7 months ago        73.9 MB

But when i run docker-compose up -d, it failed finally , and print the following error:
ERROR: readlink /var/lib/docker/overlay2/l: invalid argument

**Comment by eric2016fly** [comment]
finally, i found that it is caused by not pulling the full images via docker-compose, just run the following:
1.umount /var/lib/docker/overlay2
2.restart the docker
3. docker-compose up -d

**Comment by Hoverbear** [comment]
@eric2016fly I'm glad you figured it out! It looks like this isn't an issue that needs action so I'm closing it.
