### ISSUE TITLE
使用tidb-docker-compose部署错误

### ISSUE THREAD

**Issue by XieZiXi** [pingcap/tidb-docker-compose#37]
使用最新tidb-docker-compose部署集群，tikv启动不了，与楼上同学问题一致。
![image](https://user-images.githubusercontent.com/17958292/45347822-8fd16780-b5df-11e8-9947-9dc7c701a963.png)
tikv一直处于：restarting状态

**Comment by tennix** [comment]
Does your CentOS have selinux enabled? You can verify it by `Security options` in `docker info` output.

**Comment by RavenZZ** [comment]
一样的问题, 几个月前第一次试的时候, 能up起来, 但最近用最新的image就不行
把log-level改成了debug, docker-compose up 后, 如图tikv起来后就挂了, 看不太出什么有用的信息
![image](https://user-images.githubusercontent.com/3965218/45370135-26bb1580-b61a-11e8-9159-1239f9db56da.png)

Docker version 18.06.1-ce, build e68fc7a
docker-compose version 1.22.0, build f46880fe
CentOS Linux release 7.5.1804

**Comment by RavenZZ** [comment]
> @RavenZZ Could you comment out `max-open-files` line and set it to `1024` and then try it again? Seems I've happened to override this config when upgrading configurations to v2.0.4 in #34

this works, thanks~

**Comment by rover5269** [comment]
tikv default max-open-files is 1024，but still not works.  tikv state is restarting.

**Comment by tennix** [comment]
Could you provide the TiKV logs? @rover5269
