### ISSUE TITLE
can't comment tispark

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb-docker-compose#46]
when I comment tispark, helm raises error:

```
helm template compose > my-dockerfile
Error: render error in “tidb-docker-compose/templates/docker-compose.yml”: template: tidb-docker-compose/templates/docker-compose.yml:6:34: executing “tidb-docker-compose/templates/docker-compose.yml” at <.Values.tispark.work...>: can’t evaluate field workerCount in type interface {}
```

I have to comment it in the generated docker file.

**Comment by gregwebs** [comment]
This error means the template needs an additional check whether the intermediate (tispark) key exists.

**Comment by tennix** [comment]
Yes, we define the tispark slave in the top level of template, which may not exist.
