### ISSUE TITLE
Please confirm if docker-compose up --scale won't work 

### ISSUE THREAD

**Issue by deadjoe** [pingcap/tidb-docker-compose#51]
Just want to confirm after the default  docker-compose up and to increase the tikv won't work by issuing "docker-compose up --scale tikv0=5 "。

there are more  tikv0_X containers up but did not aggregated into the exists cluster .

It's fine if this won't work for current version.

**Comment by tennix** [comment]
Yes, IIRC `docker-compose scale` is a docker swarm feature. Currently, we don't support docker swarm. Besides the start command is not the same for all TiKV container, each TiKV has to advertise its own address to the cluster. I have no idea how to implement this in docker swarm.

If you figure this out, I'm glad to see a PR to support easy scaling TiKV. Scaling PD would be a little tricky and I don't think it's necessary to scale PD for docker-compose.

**Comment by tennix** [comment]
The docker swarm support is added by #59 which can use `scale` command to scale TiKV and TiDB.
