### ISSUE TITLE
Mark this repo and docs to DEPRECATED?

### ISSUE THREAD

**Issue by southwolf** [pingcap/tidb-docker-compose#95]
Hi TiDB team,

I found this repo has not been updated since 1 year ago. According to discussion in previous issues, `docker-compose` way seems to be deprecated and it is recommended to switch to `tiup` instead.

Should this repo and [document](https://docs.pingcap.com/tidb/stable/deploy-test-cluster-using-docker-compose#tidb-docker-compose-deployment) (still live in stable version) marked as DEPRECATED?

**Comment by AstroProfundis** [comment]
There seems to be no one maintaining this repo anymore, I think it's safe to archive it.

**Comment by tisonkun** [comment]
Thanks for your reporting! As @AstroProfundis mentioned it is to be archived, and I think @lilyjazz can share issues / PRs reflect on the doc site.

**Comment by lilyjazz** [comment]
Thank you for your suggestion.
As you said, the docker-compose way is no longer supported.
The related documents have been deleted on version 5.0 and above. [doc-pr](https://github.com/pingcap/docs/pull/5830)

**Comment by tisonkun** [comment]
@southwolf @lilyjazz as @alex-quan-001 mentioned at https://github.com/pingcap/tidb-docker-compose/pull/96#issuecomment-866683551 this repository is still under development. We will keep the repo open.

@lilyjazz @alex-quan-001 you may negotiate what to do on the doc site.

**Comment by tisonkun** [comment]
Close this issue as it is not DEPRECATED.

**Comment by lilyjazz** [comment]
Thank you for your suggestion.
We have deleted related documents in v5.0 and above to avoid misleading users. 
[doc pr](https://github.com/pingcap/docs/pull/5830)
